---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: true

  - name: install apache2 package
    yum:
      name: httpd

  - name: started apache2 service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: update servername in apache configfile
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regex: "^ServerName"
      line: ServerName 127.0.0.1
    register: httpd_servername


  - name: restating httpd server after servername's changed
    service:
      name: httpd
      state: restarted
    when: httpd_servername.changed

