---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: true

  - name: install apache2 package
    yum:
      name: httpd

  - name: started apache2 service
    service:
      name: httpd
      state: started
      enabled: yes

